name: Actions Version Tests

on:
  pull_request:

jobs:
  setup-lando-os-test:
    runs-on: ${{ matrix.os }}
    env:
      term: xterm
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        node-version:
          - '18'
        lando-version:
          - '3.x'
          - '>2'
          - '3'
          - '3.14'
          - '3.14.0'
          - 'v3.21.0-beta.10-slim'
          - '3-slim'
          - '3-stable'
          - '3-stable-slim'
          - '3-edge'
          - '3-edge-slim'
          - '3-latest'
          - '3-dev'
          - '3-dev-slim'
          - 'stable'
          - 'edge'
          - 'latest'
          - 'dev'
          - 'pm-preview'
          - 'https://github.com/lando/cli/releases/download/v3.18.0/lando-linux-x64-v3.18.0'
          - '/home/runner/work/setup-lando/setup-lando/bin/lando'
          - './bin/lando'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies and prepare
        run: |
          npm clean-install --prefer-offline --frozen-lockfile
          npm run prepare

      - name: Setup Lando version ${{ matrix.lando-version }}
        uses: ./
        with:
          lando-version: ${{ matrix.lando-version }}
