name: Windows Script Shell Tests

on:
  pull_request:

jobs:
  setup-lando-windows-shell-test:
    runs-on: windows-2022
    env:
      LANDO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        shell:
          - powershell
          - pwsh
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - if: matrix.shell == 'powershell'
        name: Execute ps1 with PowerShell 5.1
        shell: powershell
        run: |
          .\setup-lando.ps1
          lando version --all
      - if: matrix.shell == 'pwsh'
        name: Execute ps1 with PowerShell 7
        shell: pwsh
        run: |
          .\setup-lando.ps1
          lando version --all
